server:
  port: 8585

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: Reform Scan Notification Service

queue:
  notifications:
    read-connection-string: ${QUEUE_NOTIFICATIONS_READ}
    queue-name: notifications-reform
