server:
  port: 8585

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: db
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: Reform Scan Notification Service
  config:
    import: "optional:configtree:/mnt/secrets/reform-scan/"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: NotificationHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

scheduling:
  lock_at_most_for: PT10M # 10 minutes in ISO-8601
  task:
    notifications-consume:
      check:
        delay: ${NOTIFICATIONS_CONSUME_TASK_CHECK_DELAY_IN_MS} # in ms
      enabled: ${NOTIFICATIONS_CONSUME_TASK_ENABLED}
    pending-notifications:
      delay: ${PENDING_NOTIFICATIONS_TASK_DELAY_IN_MS}
      enabled: ${PENDING_NOTIFICATIONS_TASK_ENABLED}
      send-delay-in-minute: ${PENDING_NOTIFICATIONS_SEND_DELAY_IN_MINUTE}

# clients region

idam:
  s2s-auth:
    url: ${S2S_URL}

jms:
  # JMS Configuration for local dev
  application-name: BulkScanNotificationsApiDev
  enabled: ${JMS_ENABLED:false}
  namespace: ${JMS_NAMESPACE:5672}
  amqp-connection-string-template: ${JMS_AMQP_CONNECTION_TEMPLATE:amqp://localhost:%1s?amqp.idleTimeout=%2d}
  username: ${JMS_USERNAME:admin}
  password: ${JMS_PASSWORD:admin}
  receiveTimeout: ${JMS_RECEIVE_TIMEOUT:30000}
  idleTimeout: ${JMS_IDLE_TIMEOUT:30000}

# end of clients region
