server:
  port: 8585

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: Reform Scan Notification Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: NotificationHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  sleuth:
    traceId128: true

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

queue:
  notifications:
    read-connection-string: ${QUEUE_NOTIFICATIONS_READ}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5p %logger{36} [%t] %C{2} - %m%n"