server:
  port: 8585

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: Reform Scan Notification Service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_CONN_OPTIONS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: NotificationHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000

flyway:
  skip-migrations: ${FLYWAY_SKIP_MIGRATIONS}

queue:
  notifications:
    read-connection-string: ${QUEUE_NOTIFICATIONS_READ}
    max-delivery-count: ${QUEUE_NOTIFICATIONS_MAX_RETRY}

# clients region

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME:reform_scan_notification_service}

# end of clients region
