server:
  port: 8585

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

spring:
  application:
    name: Reform Scan Notification Service
