apiVersion: v2
description: A Helm chart for Reform Scan Notification Service
name: reform-scan-notification-service
home: https://github.com/hmcts/reform-scan-notification-service
version: 1.0.1
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: 3.7.7
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: servicebus
    version: 0.3.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: servicebus.enabled
