apiVersion: v2
description: A Helm chart for Reform Scan Notification Service
name: reform-scan-notification-service
home: https://github.com/hmcts/reform-scan-notification-service
version: 2.0.6
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: 4.1.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: servicebus
    version: 0.4.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: servicebus.enabled
