apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Reform Scan Notification Service
name: reform-scan-notification-service
home: https://github.com/hmcts/reform-scan-notification-service
version: 0.1.4
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
