java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NOTIFICATIONS_CONSUME_TASK_DELAY_IN_MS: 1000
    QUEUE_NAME: "notifications-staging"
    QUEUE_NOTIFICATIONS_READ: false
    PENDING_NOTIFICATIONS_TASK_DELAY_IN_MS: 500
    FLYWAY_SKIP_MIGRATIONS: false
    PENDING_NOTIFICATIONS_SEND_DELAY_IN_MINUTE: 0
  keyVaults:
    "reform-scan":
      secrets:
        - name: app-insights-instrumentation-key
          alias: azure.application-insights.instrumentation-key
        - name: error-notifications-password
          alias: clients.error-notifications.password
        - name: error-notifications-url
          alias: clients.error-notifications.url
        - name:  error-notifications-username
          alias: clients.error-notifications.username
        - name: notification-service-staging-postgres-pass
          alias: DB_PASSWORD
        - name: notification-service-staging-postgres-user
          alias: DB_USER
        - name: notification-service-staging-postgres-host
          alias: DB_HOST
        - name: notification-service-staging-postgres-port
          alias: DB_PORT
        - name: notification-service-staging-postgres-database
          alias: DB_NAME
        - name:  notification-staging-queue-listen-shared-access-key
          alias: QUEUE_READ_ACCESS_KEY
