java:
  applicationPort: 8585
  ingressHost: reform-scan-notification-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: reform-scan
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - app-insights-instrumentation-key
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
        - notification-service-POSTGRES-PASS
        - notification-service-POSTGRES-USER
        - notification-service-POSTGRES-HOST
        - notification-service-POSTGRES-PORT
        - notification-service-POSTGRES-DATABASE
        - notifications-queue-listen-connection-string

  environment:
    DB_CONN_OPTIONS: ?sslmode=require
    FLYWAY_SKIP_MIGRATIONS: true

  image: 'hmctspublic.azurecr.io/reform-scan/notification-service:latest'
