java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NOTIFICATIONS_CONSUME_TASK_DELAY_IN_MS: 1000
    STAGING_QUEUE_NOTIFICATIONS_ENABLED: true
    QUEUE_NOTIFICATIONS_READ: false
    PENDING_NOTIFICATIONS_TASK_DELAY_IN_MS: 500
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - app-insights-instrumentation-key
        - error-notifications-password
        - error-notifications-url
        - error-notifications-username
        - notification-service-POSTGRES-PASS
        - notification-service-POSTGRES-USER
        - notification-service-POSTGRES-HOST
        - notification-service-POSTGRES-PORT
        - notification-service-POSTGRES-DATABASE
        - notifications-staging-queue-listen-connection-string